### ISSUE TITLE
OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message=GL_INVALID_OPERATION error generated. No active program

### ISSUE THREAD

**Issue by dadoirie** [leon-o/iris-flw-compat#7]
getting console spammed with this message in certain areas with shaders enabled
`[Thread-39/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. No active program.'`
https://mclo.gs/VVuazQz

**Comment by leon-o** [comment]
Are there bells in that areas.Is there bells in that areas?

**Comment by emoace** [comment]
Hi, I've been having the same error. I also get the same error when around Blaze Burners. I have Oculus, Rubidium, Create, Flywheel, and this mod installed. It even happens without shaders.

I placed down a haunted bell and when I right clicked, instead of the regular animation from Create there is just flashy streaks across my screen when I look in certain directions.
![2022-10-12_20 58 16](https://user-images.githubusercontent.com/77821109/195481109-b0a4137a-3edd-42c6-a386-b361f7b3b9bb.png)


I also get the same error when around Blaze Burners.
