### ISSUE TITLE
Moving blocks are invisible with Complementary

### ISSUE THREAD

**Issue by neptunespearz** [leon-o/iris-flw-compat#71]
The complementary patch is already applied. 
Minecraft 1.20.1
Iris Flywheel compat 0.2.1
Create 0.5.1d
Iris 1.64
Complementary 4.7.2
https://github.com/leon-o/iris-flw-compat/assets/143643017/29db60f1-a387-4359-b6f7-40b50764a71b

**Comment by Gayowulf** [comment]
Can confirm this same behavior.

**System specifications:**
- OS: Ubuntu 23.04
- GPU: AMD RX 7900 XTX

- Minecraft 1.19.2
- Fabric 0.14.22
- Iris 1.6.6
- Create Fabric 0.5.1.b
- Iris Flywheel Compat 0.2.1
- Complementary 4.7.1

This only happens for me using Complementary shaders. Complementary Reimagined works fine.

**Comment by neptunespearz** [comment]
Replicated your exact versions and doesnt work for me with reimagined. also unbound, BSL, (chocapic is visible but transparent). I am using different system though, MacOS m1 pro (aarch64).

**Comment by thelyric27** [comment]
[latest.log](https://github.com/leon-o/iris-flw-compat/files/12864146/latest.log)

I have this same issue on Forge 1.19.2 with all of the shaders I have tried already.

The Flywheel rendering mode is Instancing, which worked for a large room with many waterwheels and other Create objects which were in motion, but as soon as I got on my elevator which was an actual Contraption, it turned invisible until it quit moving. I will try Batching mode to see if it has the same bug and update my post if so, but Batching gave me no noticeable performance improvement in that same room unlike Instancing.

When the contraption turns invisible, I see this error repeating in the log:
```
[21:11:48] [Render thread/INFO] [mojang/GlDebug]: OpenGL debug message: id=2, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION in glDrawElements'
[21:11:48] [Render thread/INFO] [mojang/GlDebug]: OpenGL debug message: id=2, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION in glDrawElementsInstanced'
```

My mod versions will be in the beginning of the log if anyone wants to check that, There may be some issue due to the Oculus Particle Fix mod which I am using, but I'm not sure of that, and said mod is needed to fix a pretty glaring particle rendering bug.

**Comment by amyfromearth** [comment]
Confirming this happens to me as well. 

Minecraft 1.20.1
Iris 1.6.10
Complementary Reimagined r5.0.1

**Comment by dakiba** [comment]
The strange thing is, with the rethinking-voxel I see the contraptions again, but in a bright green. everything else I dont get working. Tried a lot of shader / shaderversions and iris versions.

![Uploading 2023-12-28_00.50.11.png…]()

**Comment by dakiba** [comment]
OK, seems to be a problem with linux.
My girlfriend can play all shaders without any issues on windows .... -.-*

**Comment by dakiba** [comment]
I can use shader now, you have to disable in Performance Settings - Real-Time Shadows.

**Comment by amyfromearth** [comment]
> OK, seems to be a problem with linux. My girlfriend can play all shaders without any issues on windows .... -.-*

I have players on both Windows and Linux experiencing the issue on my server.
