### ISSUE TITLE
Complementary shaders/Euphoria patches

### ISSUE THREAD

**Issue by DaddyKami** [leon-o/iris-flw-compat#89]
please add euphoria patches for complementary shaders, since once you use those all the visual glitches imagineable appear.

would be so amazing for those really enjoying those extra features of shaders together with create

**Comment by SpacEagle17** [comment]
Developer of Euphoria Patches here o/
I hope that some support could be added somehow as many users have reported things to us while we can't do much about it. Current known options that break are: `generated normals`, `winter` (will be fixed in the next update), and `sand and moss noise` overlay (will also be fixed in the next update). From what I can see it seems that options that utilize `atlasSize` break compatibility. So I just removed that from the winter, sand, and moss settings for the next update.
As Complementary Support already exists I hope that adding it to Complementary with our Add-On won't be too difficult.
If any help is needed, I am here to assist.
